CREATE TABLE organisation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6),
    email VARCHAR(255),
    name VARCHAR(255),
    organisation_type VARCHAR(255) CHECK (organisation_type IN ('PRIVATE','PUBLIC')),
    registration_number VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    organisation_id BIGINT NOT NULL,
    parent_id BIGINT,
    email VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255) CHECK (role IN ('ADMIN','PROPRIETOR','MANAGER')),
    PRIMARY KEY (id)
);

CREATE TABLE farm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_active BOOLEAN NOT NULL,
    latitude FLOAT(53),
    longitude FLOAT(53),
    created_at TIMESTAMP(6),
    manager_id BIGINT,
    organisation_id BIGINT NOT NULL,
    address VARCHAR(255),
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    capacity INTEGER,
    is_available BOOLEAN NOT NULL,
    farm_id BIGINT NOT NULL,
    animal_category VARCHAR(255) CHECK (animal_category IN ('POULTRY','LIVESTOCK')),
    name VARCHAR(255),
    production_type VARCHAR(255) CHECK (production_type IN ('Egg','Milk','Meat')),
    PRIMARY KEY (id)
);

CREATE TABLE batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actual_end_date DATE,
    current_count INTEGER NOT NULL,
    expected_end_date DATE,
    initial_count INTEGER NOT NULL,
    mortality_count INTEGER,
    start_date DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    section_id BIGINT NOT NULL,
    updated_at TIMESTAMP(6),
    batch_number VARCHAR(255) NOT NULL UNIQUE,
    breed VARCHAR(255) NOT NULL CHECK (breed IN ('COBB_500','ROSS_308','ISA_BROWN','HY_LINE_SILVER')),
    status VARCHAR(255) NOT NULL CHECK (status IN ('PLANNED','ACTIVE','COMPLETED','ARCHIVED')),
    PRIMARY KEY (id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    current_quantity FLOAT(53) NOT NULL,
    expiry_date DATE,
    low_stock_threshold FLOAT(53) NOT NULL,
    unit_price FLOAT(53),
    farm_id BIGINT NOT NULL,
    organisation_id BIGINT,
    category VARCHAR(255) CHECK (category IN ('FEED','MEDICINE','VACCINE','EQUIPMENT')),
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE daily_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    average_weight FLOAT(53),
    eggs_collected INTEGER,
    feed_quantity_used FLOAT(53),
    historical_feed_cost FLOAT(53),
    historical_medicine_cost FLOAT(53),
    log_date DATE,
    medicine_quantity_used FLOAT(53),
    mortality_count INTEGER,
    water_quantity_used FLOAT(53),
    assigned_to_id BIGINT,
    batch_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    inventory_id BIGINT,
    medicine_inventory_id BIGINT,
    recorded_by_id BIGINT NOT NULL,
    administration_method VARCHAR(255),
    observations VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE system_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    daily_log_id BIGINT NOT NULL,
    resolved_at TIMESTAMP(6),
    resolved_by_user_id BIGINT,
    action_taken VARCHAR(255),
    alert_type VARCHAR(255) NOT NULL CHECK (alert_type IN ('FEED_UNDER_CONSUMPTION','MORTALITY_LIMIT_BREACH','PRODUCTION_YIELD_DROP','CLIMATE_STRESS')),
    diagnosis_message TEXT NOT NULL,
    resolution_category VARCHAR(255) CHECK (resolution_category IN ('VENTILATION_AND_COOLING','WATER_SYSTEM_REPAIR','MEDICATION_AND_TREATMENT','FEED_ADJUSTMENT','ENVIRONMENTAL_SANITATION','EQUIPMENT_REPAIR','FALSE_ALARM_VERIFIED')),
    resolution_notes VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN ('TRIGGERED','ACKNOWLEDGED','RESOLVED')),
    PRIMARY KEY (id)
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount FLOAT(53) NOT NULL,
    is_cash_flow BOOLEAN NOT NULL,
    transaction_date DATE NOT NULL,
    batch_id BIGINT,
    created_at TIMESTAMP(6),
    farm_id BIGINT,
    organisation_id BIGINT,
    category VARCHAR(255) CHECK (category IN ('LIVESTOCK_SALE','EQUIPMENT_PURCHASE','LABOR_COST','UTILITY_BILL','FEED_PURCHASE','MEDICINE_PURCHASE','VACCINE_PURCHASE','FEED_CONSUMPTION','MEDICINE_CONSUMPTION','VACCINE_CONSUMPTION','OTHER_INCOME','OTHER_EXPENSE')),
    description VARCHAR(255),
    type VARCHAR(255) CHECK (type IN ('CREDIT','DEBIT')),
    PRIMARY KEY (id)
);

CREATE TABLE weekly_breed_standards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    expected_body_weight FLOAT(53),
    expected_daily_feed_intake FLOAT(53) NOT NULL,
    expected_production_rate FLOAT(53),
    max_weekly_mortality_rate FLOAT(53) NOT NULL,
    week_number INTEGER NOT NULL,
    breed VARCHAR(255) NOT NULL CHECK (breed IN ('COBB_500','ROSS_308','ISA_BROWN','HY_LINE_SILVER')),
    PRIMARY KEY (id),
    UNIQUE (breed, week_number)
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    expiry_date TIMESTAMP(6) NOT NULL,
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE production_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    target_fcr FLOAT(53) NOT NULL,
    target_weeks INTEGER NOT NULL,
    batch_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    breed VARCHAR(255) NOT NULL CHECK (breed IN ('COBB_500','ROSS_308','ISA_BROWN','HY_LINE_SILVER')),
    PRIMARY KEY (id)
);

-- FOREIGN KEYS
ALTER TABLE batch ADD CONSTRAINT FK_batch_section FOREIGN KEY (section_id) REFERENCES section;
ALTER TABLE daily_log ADD CONSTRAINT FK_dl_assigned_user FOREIGN KEY (assigned_to_id) REFERENCES users;
ALTER TABLE daily_log ADD CONSTRAINT FK_dl_batch FOREIGN KEY (batch_id) REFERENCES batch;
ALTER TABLE daily_log ADD CONSTRAINT FK_dl_inventory FOREIGN KEY (inventory_id) REFERENCES inventory;
ALTER TABLE daily_log ADD CONSTRAINT FK_dl_med_inventory FOREIGN KEY (medicine_inventory_id) REFERENCES inventory;
ALTER TABLE daily_log ADD CONSTRAINT FK_dl_recorded_user FOREIGN KEY (recorded_by_id) REFERENCES users;
ALTER TABLE farm ADD CONSTRAINT FK_farm_manager FOREIGN KEY (manager_id) REFERENCES users;
ALTER TABLE farm ADD CONSTRAINT FK_farm_org FOREIGN KEY (organisation_id) REFERENCES organisation;
ALTER TABLE inventory ADD CONSTRAINT FK_inv_farm FOREIGN KEY (farm_id) REFERENCES farm;
ALTER TABLE inventory ADD CONSTRAINT FK_inv_org FOREIGN KEY (organisation_id) REFERENCES organisation;
ALTER TABLE production_target ADD CONSTRAINT FK_prod_target_batch FOREIGN KEY (batch_id) REFERENCES batch;
ALTER TABLE section ADD CONSTRAINT FK_section_farm FOREIGN KEY (farm_id) REFERENCES farm;
ALTER TABLE system_alert ADD CONSTRAINT FK_alert_batch FOREIGN KEY (batch_id) REFERENCES batch;
ALTER TABLE system_alert ADD CONSTRAINT FK_alert_dl FOREIGN KEY (daily_log_id) REFERENCES daily_log;
ALTER TABLE transaction ADD CONSTRAINT FK_txn_batch FOREIGN KEY (batch_id) REFERENCES batch;
ALTER TABLE transaction ADD CONSTRAINT FK_txn_farm FOREIGN KEY (farm_id) REFERENCES farm;
ALTER TABLE transaction ADD CONSTRAINT FK_txn_org FOREIGN KEY (organisation_id) REFERENCES organisation;
ALTER TABLE users ADD CONSTRAINT FK_user_org FOREIGN KEY (organisation_id) REFERENCES organisation;
ALTER TABLE users ADD CONSTRAINT FK_user_parent FOREIGN KEY (parent_id) REFERENCES users;create table batch (actual_end_date date, current_count integer not null, expected_end_date date, initial_count integer not null, mortality_count integer, start_date date not null, created_at timestamp(6) not null, id bigint generated by default as identity, section_id bigint not null, updated_at timestamp(6), batch_number varchar(255) not null unique, breed varchar(255) not null check ((breed in ('COBB_500','ROSS_308','ISA_BROWN','HY_LINE_SILVER'))), status varchar(255) not null check ((status in ('PLANNED','ACTIVE','COMPLETED','ARCHIVED'))), primary key (id));
create table daily_log (average_weight float(53), eggs_collected integer, feed_quantity_used float(53), historical_feed_cost float(53), historical_medicine_cost float(53), log_date date, medicine_quantity_used float(53), mortality_count integer, water_quantity_used float(53), assigned_to_id bigint, batch_id bigint not null, created_at timestamp(6), id bigint generated by default as identity, inventory_id bigint, medicine_inventory_id bigint, recorded_by_id bigint not null, administration_method varchar(255), observations varchar(255), primary key (id));
create table farm (is_active boolean not null, latitude float(53), longitude float(53), created_at timestamp(6), id bigint generated by default as identity, manager_id bigint, organisation_id bigint not null, address varchar(255), name varchar(255) not null unique, primary key (id));
create table inventory (current_quantity float(53) not null, expiry_date date, low_stock_threshold float(53) not null, unit_price float(53), farm_id bigint not null, id bigint generated by default as identity, organisation_id bigint, category varchar(255) check ((category in ('FEED','MEDICINE','VACCINE','EQUIPMENT'))), name varchar(255) not null, unit varchar(255), primary key (id));
create table organisation (created_at timestamp(6), id bigint generated by default as identity, email varchar(255), name varchar(255), organisation_type varchar(255) check ((organisation_type in ('PRIVATE','PUBLIC'))), registration_number varchar(255), primary key (id));
create table password_reset_tokens (expiry_date timestamp(6) not null, id bigint generated by default as identity, email varchar(255) not null, token varchar(255) not null unique, primary key (id));
create table production_target (target_fcr float(53) not null, target_weeks integer not null, batch_id bigint not null unique, created_at timestamp(6) not null, id bigint generated by default as identity, breed varchar(255) not null check ((breed in ('COBB_500','ROSS_308','ISA_BROWN','HY_LINE_SILVER'))), primary key (id));
create table section (capacity integer, is_available boolean not null, farm_id bigint not null, id bigint generated by default as identity, animal_category varchar(255) check ((animal_category in ('POULTRY','LIVESTOCK'))), name varchar(255), production_type varchar(255) check ((production_type in ('Egg','Milk','Meat'))), primary key (id));
create table system_alert (batch_id bigint not null, created_at timestamp(6) not null, daily_log_id bigint not null, id bigint generated by default as identity, resolved_at timestamp(6), resolved_by_user_id bigint, action_taken varchar(255), alert_type varchar(255) not null check ((alert_type in ('FEED_UNDER_CONSUMPTION','MORTALITY_LIMIT_BREACH','PRODUCTION_YIELD_DROP','CLIMATE_STRESS'))), diagnosis_message TEXT not null, resolution_category varchar(255) check ((resolution_category in ('VENTILATION_AND_COOLING','WATER_SYSTEM_REPAIR','MEDICATION_AND_TREATMENT','FEED_ADJUSTMENT','ENVIRONMENTAL_SANITATION','EQUIPMENT_REPAIR','FALSE_ALARM_VERIFIED'))), resolution_notes varchar(255), status varchar(255) not null check ((status in ('TRIGGERED','ACKNOWLEDGED','RESOLVED'))), primary key (id));
create table transaction (amount float(53) not null, is_cash_flow boolean not null, transaction_date date not null, batch_id bigint, created_at timestamp(6), farm_id bigint, id bigint generated by default as identity, organisation_id bigint, category varchar(255) check ((category in ('LIVESTOCK_SALE','EQUIPMENT_PURCHASE','LABOR_COST','UTILITY_BILL','FEED_PURCHASE','MEDICINE_PURCHASE','VACCINE_PURCHASE','FEED_CONSUMPTION','MEDICINE_CONSUMPTION','VACCINE_CONSUMPTION','OTHER_INCOME','OTHER_EXPENSE'))), description varchar(255), type varchar(255) check ((type in ('CREDIT','DEBIT'))), primary key (id));
create table users (is_active boolean not null, created_at timestamp(6), id bigint generated by default as identity, organisation_id bigint not null, parent_id bigint, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255) check ((role in ('ADMIN','PROPRIETOR','MANAGER'))), primary key (id));
create table weekly_breed_standards (expected_body_weight float(53), expected_daily_feed_intake float(53) not null, expected_production_rate float(53), max_weekly_mortality_rate float(53) not null, week_number integer not null, id bigint generated by default as identity, breed varchar(255) not null check ((breed in ('COBB_500','ROSS_308','ISA_BROWN','HY_LINE_SILVER'))), primary key (id), unique (breed, week_number));
alter table if exists batch add constraint FKc27gcm2vo7xh8l0xo6cnq86oh foreign key (section_id) references section;
alter table if exists daily_log add constraint FKh3q67uqfn3q2wkknwfdc5bg3f foreign key (assigned_to_id) references users;
alter table if exists daily_log add constraint FKikau6x2kbuwkk0m7klrwb86g foreign key (batch_id) references batch;
alter table if exists daily_log add constraint FKajwnv40fc4pqppxfjt1bv5sl4 foreign key (inventory_id) references inventory;
alter table if exists daily_log add constraint FKo4qge2r87p78o98qhvw5wn1se foreign key (medicine_inventory_id) references inventory;
alter table if exists daily_log add constraint FKq8l5ddcpphvmionjif2q4ld5r foreign key (recorded_by_id) references users;
alter table if exists farm add constraint FKq3aq63gf32gr6v8ckx1dfb6w8 foreign key (manager_id) references users;
alter table if exists farm add constraint FKikix7avai9km3g78goou751i0 foreign key (organisation_id) references organisation;
alter table if exists inventory add constraint FK8m7gtfy5yk09kwd92fw6sxkf8 foreign key (farm_id) references farm;
alter table if exists inventory add constraint FKjfwp3ibaa95usou5nlbhfasm7 foreign key (organisation_id) references organisation;
alter table if exists production_target add constraint FKqnnwckawgdi7mv95fy9qikuen foreign key (batch_id) references batch;
alter table if exists section add constraint FKe4jb5gqtgg793gs31xyufgwbl foreign key (farm_id) references farm;
alter table if exists system_alert add constraint FK3dtkn3h4rejo61h2d52ubihwp foreign key (batch_id) references batch;
alter table if exists system_alert add constraint FKlo1nniu2aorq19wyi5qkm1o foreign key (daily_log_id) references daily_log;
alter table if exists transaction add constraint FK488qkru416qg1j5djdbr4honw foreign key (batch_id) references batch;
alter table if exists transaction add constraint FKkmp67krfbj3k9m9kcbmbyh03a foreign key (farm_id) references farm;
alter table if exists transaction add constraint FKf2j4x9sc36ehmli3ul31awlpi foreign key (organisation_id) references organisation;
alter table if exists users add constraint FKhb3nv5nv0xr3wpuxfsb2jft1s foreign key (organisation_id) references organisation;
alter table if exists users add constraint FK4ty2qb76gscl4oi0yugg5gywc foreign key (parent_id) references users;
